### ISSUE TITLE
Error with the function igloo

### ISSUE THREAD

**Issue by andre-alejandro** [Shaaaaaaaaaron/Minecraft-Chaos-Datapack#1]
When I start the server, the console shows a failed loading of the igloo function and when I am in the game nothing happens when I select it. 
![Captura de pantalla 2021-03-13 133933](https://user-images.githubusercontent.com/40127869/111040596-a69be380-8401-11eb-81f9-cad8f107a2cc.png)

**Comment by Shaaaaaaaaaron** [comment]
There was a missing bracket in one of the commands, fixed it.
