### ISSUE TITLE
The message with some info isn't showing

### ISSUE THREAD

**Issue by mirns-cooper** [Shaaaaaaaaaron/Minecraft-Chaos-Datapack#5]
Erm...What the Sigma? The message with some info isn't showing it's like there is no datapack. But when I did /datapack i saw that it was i even did /reload. SOS SOS SOS SOS SOS SOS SOS SOS SOS SOS HELP HELP HELP HELP HELP HELP HELP HELP HELP HELP HELP HELP HELP HELP HELP HELP

Love you!

**Comment by Shaaaaaaaaaron** [comment]
I'm aware of this and currently trying to get a version working for 1.21!
